# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4d2fd5e55fca0462fac7406da68258754386c1bf7b7f5dc0f1931947c1a598c75e04b5bddb130922adb5427299956b0f278b2c7fcb71841ce51b93dd2983525

test:
  secret_key_base: e0b6b9c6e881ea8b3a11eaaf0b37fdef20a709ed8a46b883f5b3fd148ad1cad7f6cbc9b988223afb7cc4e85cee6b3a31c72febd85275eac474ecf1506b42163a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
